INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis10','Ponce10','lpctest10@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis11','Ponce11','lpctest11@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis12','Ponce12','lpctest12@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis13','Ponce13','lpctest13@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis14','Ponce14','lpctest14@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis15','Ponce15','lpctest15@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis16','Ponce16','lpctest16@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis17','Ponce17','lpctest17@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis18','Ponce18','lpctest18@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis19','Ponce19','lpctest19@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis20','Ponce20','lpctest20@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis21','Ponce21','lpctest21@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis22','Ponce22','lpctest22@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis23','Ponce23','lpctest23@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis24','Ponce24','lpctest24@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis25','Ponce25','lpctest25@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis26','Ponce26','lpctest26@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis27','Ponce27','lpctest27@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis28','Ponce28','lpctest28@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis29','Ponce29','lpctest29@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis30','Ponce30','lpctest30@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis31','Ponce31','lpctest31@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis32','Ponce32','lpctest32@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis33','Ponce33','lpctest33@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis34','Ponce34','lpctest34@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis35','Ponce35','lpctest35@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis36','Ponce36','lpctest36@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis37','Ponce37','lpctest37@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis38','Ponce38','lpctest38@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis39','Ponce39','lpctest39@gmail.com',	SYSDATE,'');
INSERT INTO CLIENTES (id,nombre,apellido,email,create_at,foto) VALUES (CLIENTES_SEQ.NEXTVAL,	'Luis40','Ponce40','lpctest40@gmail.com',	SYSDATE,'');

INSERT INTO PRODUCTOS (id,nombre,precio,create_at) values (PRODUCTOS_SEQ.NEXTVAL,'Panasonic Pantalla LCD',259990,SYSDATE);
INSERT INTO PRODUCTOS (id,nombre,precio,create_at) values (PRODUCTOS_SEQ.NEXTVAL,'Sony cámara digital DSC-W320B',123490,SYSDATE);
INSERT INTO PRODUCTOS (id,nombre,precio,create_at) values (PRODUCTOS_SEQ.NEXTVAL,'Apple Ipod shuffle',1499990,SYSDATE);
INSERT INTO PRODUCTOS (id,nombre,precio,create_at) values (PRODUCTOS_SEQ.NEXTVAL,'Sony Notebook Z110',37990,SYSDATE);
INSERT INTO PRODUCTOS (id,nombre,precio,create_at) values (PRODUCTOS_SEQ.NEXTVAL,'HP Multifuncional F2280',69990,SYSDATE);
INSERT INTO PRODUCTOS (id,nombre,precio,create_at) values (PRODUCTOS_SEQ.NEXTVAL,'Bicicleta Bianchi aro 26',69990,SYSDATE);
INSERT INTO PRODUCTOS (id,nombre,precio,create_at) values (PRODUCTOS_SEQ.NEXTVAL,'Mica cómida 5 cajones',299990,SYSDATE);

INSERT INTO FACTURAS (id,descripcion,observacion,cliente_id,create_at) VALUES (FACTURAS_SEQ.NEXTVAL,'Factura equipos de oficina',null,1,SYSDATE);
INSERT INTO FACTURAS_ITEMS (id,cantidad,factura_id,producto_id) values (FACTURAS_ITEM_SEQ.NEXTVAL,1,1,1);
INSERT INTO FACTURAS_ITEMS (id,cantidad,factura_id,producto_id) values (FACTURAS_ITEM_SEQ.NEXTVAL,2,1,4);
INSERT INTO FACTURAS_ITEMS (id,cantidad,factura_id,producto_id) values (FACTURAS_ITEM_SEQ.NEXTVAL,1,1,5);
INSERT INTO FACTURAS_ITEMS (id,cantidad,factura_id,producto_id) values (FACTURAS_ITEM_SEQ.NEXTVAL,1,1,7);

INSERT INTO FACTURAS (id,descripcion,observacion,cliente_id,create_at) VALUES (FACTURAS_SEQ.NEXTVAL,'Factura Bicicleta','Alguna nota importante',2,SYSDATE);
INSERT INTO FACTURAS_ITEMS (id,cantidad,factura_id,producto_id) values (FACTURAS_ITEM_SEQ.NEXTVAL,3,2,6);
